version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi-admin
    healthcheck:
      test: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    expose:
      - 6379
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/fastapi-admin
      REDIS_URL: redis://redis:6379/0
    ports:
      - '8000:8000'
    depends_on:
      - mysql
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0
