name: deploy
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: fastapi-admin
  examples:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.DEVELOPMENT_AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.DEVELOPMENT_AWS_DEFAULT_REGION }}
          application_name: simple-admin-portal-deployment
          environment_name: Simpleadminportaldeployment-env
          version_label: "v1.0.0"
